### ISSUE TITLE
Other platforms

### ISSUE THREAD

**Issue by apowers313** [imbaniac/awesome-blockchain#11]
Not sure if these don't fit your criteria and were excluded for a reason... but on the off chance that they weren't considered:

From the [DID Spec](https://w3c-ccg.github.io/did-method-registry/):
* VeresOne
* IPFS
* Sovrin

Others:
* [IPDB](https://medium.com/ipdb-blog/ipdb-announced-as-public-planetary-scale-blockchain-database-95082da82e84)
* [VeChainThor](https://medium.com/@vechainofficial/an-open-letter-from-sunny-lu-ceo-on-vechainthor-platform-b52d47cd0efd)

**Comment by imbaniac** [comment]
IPFS isn't blockchain

[Added Vechain and Veres](https://github.com/imbaniac/awesome-blockchain/commit/c93298ad2455e06d2ab1597abed2e2a328f13e6f) but others projects seem not alive.
